" Environment - some directories need to be created: 'mkdir -p "$XDG_DATA_HOME"/vim/{undo,swap,backup,spell}' 
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" General Settings
syntax enable
set number relativenumber
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
" set autoindent
" set smartindent
" set nowrap
" set smartcase
" set noswapfile
" set nobackup
" set undodir=~/.vim/undodir
" set undofile
set incsearch
set laststatus=2 " Status line

" Colorscheme
colorscheme elflord
" set background=dark
hi Normal guibg=NONE ctermbg=NONE

" Autocompletion
set wildmode=longest,list,full

" Disable automatic commment on newline
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

let g:netrw_altv=1
